name: Package

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '14' # 使用适当的Node.js版本
    - run: npm install
    # - run: npm run build
    - run: zip -r build.zip . -x ".git/*"
    - uses: actions/upload-artifact@v2
      with:
        name: build
        path: build.zip

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: success() && github.event_name != 'pull_request'
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: build
    - run: ls -a

    # You may pin to the exact commit or the version.
    # uses: AzulGarza/sync-repos@5ac4e9f53300b7d94fd653d25ba3456b06963b6a
    - uses: FedericoGarza/sync-repos@main
      with:
        # The GitHub repository where the files or directories need to be updated.
        target-repo: https://github.com/coder-hank/test-action
        # Path of the target file or directory in the target repository where the changes need to be reflected. It can be a file or a directory.
        target-path: /
        # Local path of the file or directory that contains the changes to be propagated. It can be a file or a directory.
        source-path: ./
        # Name of the new branch to be created for the changes.
        branch-name: master
        # A GitHub token with appropriate permissions to create and manage PRs.
        github-token: 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
        # Message for the commit that includes the changes.
        commit-message: 上传文件
        # The branch that the changes should be based off of. If not provided, defaults to 'main'.
        base-branch: # optional, default is main
        # Labels to be applied to the PR for better categorization. Defaults to 'documentation' if not provided.
        label: 11 # optional, default is documentation
        # The email address associated with the GitHub account performing the action. This will be used to associate the commits and pull request with this user.
        user-email: 15501259989@163.com
        # The username of the GitHub account performing the action. This will be reflected in the commits and pull request.
        user-name: coder-hank
          